route:
  receiver: 'telslack'
  repeat_interval: 1h
  group_by: [alertname]

receivers:
  - name: 'telslack'
    telegram_configs:
      - api_url: https://api.telegram.org
        bot_token: '7088353321:AAFln2PunhIE8f0w0yVDfSzHOS52wMTac24'
        chat_id: -4126980024
    email_configs:
      - smarthost: monitoring.mosalam.com:8025
        from: 'prometheus@mosalam.com'
        to: 'slack@mailrise.xyz'
        require_tls: false
