version: '3.8'

volumes:
  prometheus-data: {}
  alertmanager-data: {}

services:
#  node_exporter:
#    image: quay.io/prometheus/node-exporter:latest
#    container_name: node_exporter_monitoring_server
#    command:
#      - '--path.rootfs=/host'
#    network_mode: host
#    pid: host
#    restart: unless-stopped
#    volumes:
#      - '/:/host:ro,rslave'

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - '9090:9090'
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
      - ./prometheus/rules.yml:/etc/prometheus/rules.yml
    command:
      - '--web.enable-lifecycle'
      - '--config.file=/etc/prometheus/prometheus.yml'
        #      - '--web.enable-admin-api'

  pve-exporter:
    image: prompve/prometheus-pve-exporter:latest
    container_name: pve-exporter
    ports:
      - '9221:9221'
    restart: unless-stopped
    volumes:
      - ./pve/pve.yml:/etc/prometheus/pve.yml

  mailrise:
    image: yoryan/mailrise:latest
    container_name: mailrise
    ports:
      - '8025:8025'
    restart: unless-stopped
    volumes:
      - ./mailrise/mailrise.conf:/etc/mailrise.conf

  alertmanager:
    image: quay.io/prometheus/alertmanager:latest
    container_name: alertmanager
    ports:
      - "9093:9093"
    restart: unless-stopped
    volumes:
      - ./alertmanager/alertmanager.yml:/etc/alertmanager/alertmanager.yml 
      - alertmanager-data:/data
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400
