global:
  scrape_interval: 10s
  evaluation_interval: 15s

rule_files:
  - 'rules.yml'

alerting:
  alertmanagers:
  - static_configs:
    - targets:
       - monitoring.mosalam.com:9093

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'servers'
    static_configs:
      - targets: ['cpanel10.mosalam.com:9100']
      - targets: ['erp.almarinelogistic.com:9100']
      - targets: ['49.12.59.138:9100']
  - job_name: 'HetznerCloudPVE'
    static_configs:
      - targets:
        - prox3.mosalam.com   # Proxmox3
        - proxenter.mosalam.com  # ProxmoxEnter
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: monitoring.mosalam.com:9221
#  - job_name: 'MoroccoPVE'
#    static_configs:
#      - targets:
#        - 192.168.0.31
#        - 192.168.0.32
#        - 192.168.0.33
#        - 192.168.0.34
#    metrics_path: /pve
#    params:
#      module: [default]
#    relabel_configs:
#      - source_labels: [__address__]
#        target_label: __param_target
#      - source_labels: [__param_target]
#        target_label: instance
#      - target_label: __address__
#        replacement: 41.143.12.212:9221
