groups:
  - name: alert_rules
    rules:
      - alert: InstanceDown
        expr: up == 0
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} of {{ $labels.job }} is down"
          description: "{{ $labels.instance }} of {{ $labels.job }} has been down for more than 5 minutes."
